# Generated by Django 4.1 on 2022-08-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_engine', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='body',
        ),
    ]
