# Generated by Django 4.1 on 2022-08-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_engine', '0007_rename_post_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='post_engine.post'),
            preserve_default=False,
        ),
    ]
