# Generated by Django 4.1 on 2022-08-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_engine', '0010_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_on',
        ),
    ]
