# Generated by Django 4.1 on 2022-08-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_engine', '0015_alter_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
