# Generated by Django 4.1 on 2022-08-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_engine', '0016_comment_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='date',
        ),
    ]
