# Generated by Django 4.1 on 2022-08-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_engine', '0017_alter_post_options_rename_created_on_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_on',
        ),
    ]
