# Generated by Django 4.1 on 2022-08-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_engine', '0018_alter_post_options_rename_date_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
