# Generated by Django 4.0.6 on 2022-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0002_rename_profiel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
